# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: tothemoon-post
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: tothemoon-post
#   template:
#     metadata:
#       labels:
#         app: tothemoon-post
#     spec:
#       terminationGracePeriodSeconds: 30
#       containers:
#       - name: tothemoon-post
#         image: tristanpostley/tothemoon-post:${{github.run_number}}
#         imagePullPolicy: "Always"
#         ports:
#         - containerPort: 80
#         resources:
#           requests:
#             cpu: 250m
#             memory: 64Mi
#           limits:
#             cpu: 500m
#             memory: 256Mi

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: tothemoon-post
# spec:
#   ports:
#   - port: 80
#   selector:
#     app: tothemoon-post
